gantt
    title Objetivo 2
    dateFormat   YYYY-MM-DD
    section Theoretical Stage
    Make Invitation Letter                                   :a1, 2022-12-13, 2022-12-17 
    Correct and Select Question for interview                :a2, 2022-12-13, 2022-12-17
    Send invitation letters and wait for answers             :a3, after a2, 2022-12-24
    Vacations                                                :a4, after a3, 2023-01-14
    Schedule Interviews during Vacations                     :a5, 2022-12-27, 2023-01-14
    Carry out Interviews                                     :a6, after a5, 2023-01-31