gantt
    title Objective 2 Gantt Chart
    dateFormat   YYYY-MM-DD
    section Theoretical Stage
    3.4.1 dAertrycke et alii Example description and explanation       :a1, 2021-12-13, 1d
    Study Pyscipopt, Gekko, Gurobi libraries  :a2, 2021-12-15, 1d
    section Validation Stage
    Find 3.4.1 Example solution  :a3, 2021-12-15, 2d
    Description of problem and solution :a4, 2021-12-17, 1d
    CO2 budget Explication        :a5, 2021-12-20, 2d
    Rest of objetive 2           :a6, 2021-12-22, 2021-12-31