gantt
    title Project Gantt Chart
    dateFormat   YYYY-MM-DD
    section Theoretical Stage
    Literature Review               :a1, 2022-03-15, 52w
    Theoretical Examples            :a2, 2022-09-15, 52w
    (O1) Existence and welfare analysis  :a3, after a1, 2024-09-15
    (O2) Applied Example                 :a4, 2022-09-15, 2024-03-15
    section Validation Stage
    Experiment design               :a6, 2022-12-15, 52w
    (O3) Experiment validation           :a7, after a2, 2025-03-15